# Generated by Django 4.1.3 on 2022-11-28 08:12

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimages',
            name='image',
            field=models.ImageField(upload_to='images', validators=[api.validators.validate_file_size]),
        ),
    ]
